# Generated by Django 4.0.2 on 2022-02-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sumary',
            field=models.TextField(default='capivara'),
        ),
    ]
